LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE     := ed25519
LOCAL_C_INCLUDES := $(LOCAL_PATH)/ed25519
LOCAL_SRC_FILES  := ed25519/ed25519.c
include $(BUILD_STATIC_LIBRARY)


include $(CLEAR_VARS)

LOCAL_MODULE     := su
LOCAL_C_INCLUDES := $(LOCAL_PATH)/ed25519
LOCAL_SRC_FILES  := su.cc hexadecimal.cc
LOCAL_CPP_EXTENSION := .cc
LOCAL_STATIC_LIBRARIES := ed25519
include $(BUILD_EXECUTABLE)
